---
- name: Manage IAM users and groups
  hosts: localhost

  vars_files:
    # groups.yml contains all the IAM groups that will be created.
    - 'vars/groups.yml'
    # users.yml contains all the IAM users that will be created
    # and their group assignment.  Edit this file before running
    # the Job Template so that your user names are unique.
    - 'vars/users.yml'

  vars:
    sidpasswd: "{{ password }}"
    
  gather_facts: False
  tasks:
    - name: Statefully manage IAM groups
      iam:
        iam_type: group
        name: "{{ item }}"
        state: "{{ group_opts.state }}"
      with_items: 
        - "{{ aws_groups }}"
      register: new_groups

    - name: Create IAM users and group assignments.
      iam:
        iam_type: user
        name: "{{ item.name }}"
        state: "{{ user_opts.state }}"
        groups: "{{ item.aws_groups }}"
        password: "{{ sidpasswd }}"
      loop: "{{ users }}"
